// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rvmakybwcwpqdjgwlizu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ2bWFreWJ3Y3dwcWRqZ3dsaXp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0OTI3NjEsImV4cCI6MjA3MzA2ODc2MX0.PVJzJHgHmfUc4Bso1dxt4hoa0ch2X1ziieWRUZRllRI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});